name: Upload Python Package to PyPI

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel twine
      - name: Check for version change in pyproject.toml
        id: check-version
        uses: maybe-hello-world/pyproject-check-version@v4
        with:
          pyproject-path: "./pyproject.toml"
      - name: Build and Publish Package
        if: steps.check-version.outputs.local_version_is_higher
        run: |
          python setup.py sdist bdist_wheel
          twine check dist/*
          twine upload --repository-url https://upload.pypi.org/legacy/ dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}